### ISSUE TITLE
cannot read property "description" of undefined

### ISSUE THREAD

**Issue by macrozone** [marc-rutkowski/storybook-addon-props#1]
In Doc.js i receive an error cannot read property "description" of undefined

it reads  info = data.info; but info is undefined. The description would be directly on data.

**Comment by marc-rutkowski** [comment]
I already encounter this problem.
It appears when component infos are not correctly extracted by react-docgen.
At least I have to catch this error and provide a better user feedback!

But if you can provides some sample code (component and story) to help me reproduce the bug I can maybe find a fix.
First of all are you using PropTypes or Flow type annotations?

**Comment by marc-rutkowski** [comment]
@macrozone: can you test the new version (2.0.3) ?

It displays a message instead of breaking when something goes wrong while extracting component metadata.

**Comment by macrozone** [comment]
thx, I'll check
