### ISSUE TITLE
display each of the types in a union

### ISSUE THREAD

**Issue by k4b7** [marc-rutkowski/storybook-addon-props#14]
Using
```
type Props {
    option?: 'foo' | 'bar',
}
```
all that shows up in the "Type" column is "union".  

The desired behavior would be to display `'foo' | 'bar'`.

**Comment by marc-rutkowski** [comment]
Hi @kevinbarabash 
The latest release (3.0.4) should fix this.

Let me know...

**Comment by k4b7** [comment]
@marc-rutkowski the 3.0.4 release of storybook?  The most recent release of storybook-addon-props is 2.0.3.

**Comment by marc-rutkowski** [comment]
sorry @kevinbarabash, I meant release of the storybook-addon-props package on npm

**Comment by k4b7** [comment]
I didn't realize that there was different versioning.  Thanks :)
