### ISSUE TITLE
Addon with injectstyles - not showing the props

### ISSUE THREAD

**Issue by ghost** [marc-rutkowski/storybook-addon-props#16]
If we inject styles in our component we are not available to see the props. Is there any workaround?
```
import styles from "./styles.js";
class test extends Component {
    constructor(props) {
    }
    static propTypes = {
        test: PropTypes.string
    };

    render() {
        return (
            <h1>Hello</h1>
        );
    }
}
export default injectSheet(styles)(test);
```

![image](https://user-images.githubusercontent.com/35451708/36024079-e006d31a-0d8e-11e8-8f31-e8f50a2a8c8c.png)

**Comment by marc-rutkowski** [comment]
Hi @DuarteAppical,
I think it doesn't work because your component is now wrapped with styles.
Try to also export the original component class :
```
export class test extends Component {
```
then use it into your stories like this:
```
import {test}, StyledTest from 'test';

storiesOf('test', module).addWithDoc(
  'default',
  test, // <- pass the original component to let react-docgen get the props
  'it should render my test component',
  () => <StyledTest test="something" />
);
```

Let me know if it works!

**Comment by ghost** [comment]
Hi @marc-rutkowski 

I was suspecting... but the way you are suggesting is to export 2 times right?

Like:
export class test extends Component {
    constructor(props) {
    }
    static propTypes = {
        test: PropTypes.string
    };

    render() {
        return (
            <h1>Hello</h1>
        );
    }
}
export default injectSheet(styles)(test);

But then I question about performance. Being exporting 2 elements... What do you think?

**Comment by marc-rutkowski** [comment]
That's right, you need to export the original component and the wrapped version.
But I don't think there is any noticeable impact on performance by doing this.

**Comment by marc-rutkowski** [comment]
Closing this for now.
Feel free to re-open if u have other questions.
