### ISSUE TITLE
Contact the maintainers of storybook

### ISSUE THREAD

**Issue by ndelangen** [marc-rutkowski/storybook-addon-props#7]
Hey! awesome plugin, Can you join us in the storybook slack?
https://storybooks-slackin.herokuapp.com/

That way we can keep you updated on the upcoming 3.0.0 release! 

❤️ storybook team

**Comment by marc-rutkowski** [comment]
Hi @ndelangen and thanks for the invitation!
See you there :)

And I just want to say that I'm very impressed with all the work that you and other contributors have done this last few weeks to give a new life to the storybook project! 👍 
I'm looking forward to switch to v3 and do some contributions.
😃
